services:
  web:
    build:
      context: ./frontend
    ports:
      - 3002:80
    depends_on:
      - video-services

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: video
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d video"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  video-services:
    build:
      context: ./backend/video-go
    ports:
      - 8081:8080
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/video
      - GIN_MODE=release
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: