services:
  web:
    build:
      context: ./frontend
    ports:
      - 3002:80
    depends_on:
      - video-services
      - auth-services

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: video_sharing
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d video_sharing"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  auth-services:
    build:
      context: ./backend/auth-java
    ports:
      - 8082:5001
    depends_on:
      postgres:
        condition: service_healthy
    

  video-services:
    build:
      context: ./backend/video-go
    ports:
      - 8081:5000
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/video_sharing
      - GIN_MODE=release

      # MIGRATE=auto; migrate but didnt drop table
      # MIGRATE=drop; drop table and migrate 
      - MIGRATE=auto
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: